### ISSUE TITLE
Programmatically offset shape size by strokeWidth

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/reline#1]

**Comment by elrumordelaluz** [comment]
Just found this issue trying to add the ability to control the `strokeLinecap` and `strokeLinejoin` [here](https://github.com/elrumordelaluz/reline/blob/ending-shape/src/Line.js#L21-L22) and didn't PR because of this.

[Playing here](https://github.com/elrumordelaluz/reline/blob/ending-shape/src/Line.js#L49-L55) offsetting the `viewBox` but is complicated in _Components_ which shapes init with `[0, ...` (`plus`, `burger` for example).

**Comment by jxnblk** [comment]
Interesting. I wasn't thinking of changing the viewBox attribute as that would break the 16x16 grid. I was more think that there would be a calculated margin value and the shapes object would be a function that accepted that margin
